# =================================
# Server
# =================================
server:
    port: 8080
    servlet:
      context-path: /v1
# =================================
# Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/realmeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
# =================================
# Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO

realmeet:
    taskExecutor:
      pool:
        coreSize: 20
        maxSize: 20