# =================================
# Server
# =================================
server:
    port: 8080
    servlet:
      context-path: /v1
# =================================
# Spring
# =================================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bluemeet??createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
# =================================
# Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: ERROR